// src/BlazorCustomElements/samples/angular-app-with-blazor/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: `
    <div class="content">
      <h1>Welcome to {{title}}!</h1>
      <p>This is an Angular application that can also host Blazor components.</p>
      <p>
        <button (click)="addBlazorCounter()">Add Blazor counter</button>
        <button (click)="removeBlazorCounter()">Remove Blazor counter</button>
      </p>

      <div *ngFor="let counter of blazorCounters">
        <my-blazor-counter [attr.title]="counter.title"
                    [attr.increment-amount]="counter.incrementAmount">
        </my-blazor-counter>
      </div>
    </div>
  `,
  styles: []
})
export class AppComponent {
  title = 'angular-app-with-blazor';

  blazorCounters: any[] = [];
  nextCounterIndex = 1;

  addBlazorCounter() {
    const index = this.nextCounterIndex++;
    this.blazorCounters.push({
      title: `Counter ${index}`,
      incrementAmount: index,
    });
  }

  removeBlazorCounter() {
    this.blazorCounters.pop();
  }
}

// src/BlazorCustomElements/samples/react-app-with-blazor/src/App.js
import React, { useState } from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  const [nextCounterIndex, setNextCounterIndex] = useState(1);
  const [blazorCounters, setBlazorCounters] = useState([]);
  const addBlazorCounter = () => {
    const index = nextCounterIndex;
    setNextCounterIndex(index + 1);
    setBlazorCounters(blazorCounters.concat([{
      title: `Counter ${index}`,
      incrementAmount: index,
    }]));
  };
  const removeBlazorCounter = () => {
    setBlazorCounters(blazorCounters.slice(0, -1));
  };

  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          <button onClick={addBlazorCounter}>Add Blazor counter</button> &nbsp;
          <button onClick={removeBlazorCounter}>Remove Blazor counter</button>
        </p>

        {blazorCounters.map(counter =>
          <div key={counter.title}>
            <my-blazor-counter title={counter.title} increment-amount={counter.incrementAmount}></my-blazor-counter>
          </div>
        )}

        
      </header>
    </div>
  );
}

export default App;
